version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    groups:
      runtime-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"
          - "org.http4k:http4k-core:*"
          - "org.jetbrains.kotlin.jvm:*"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    groups:
      other-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "io.github.lsd-consulting:*"
          - "org.http4k:http4k-core:*"
          - "org.jetbrains.kotlin.jvm:*"
