# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Test dependencies - does not trigger semantic releases (processed first)
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "test"  # Does not trigger semantic release
    open-pull-requests-limit: 5
    groups:
      testing-dependencies:
        patterns:
          - "org.junit.jupiter:*"
          - "org.assertj:*"
        update-types:
          - "minor"
          - "patch"

  # Production dependencies - triggers semantic releases (fallback for everything else)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"  # Triggers PATCH release
    open-pull-requests-limit: 10
    groups:
      lsd-dependencies:
        patterns:
          - "io.github.lsd-consulting:*"
        update-types:
          - "minor"
          - "patch"

      http4k-dependencies:
        patterns:
          - "org.http4k:*"
        update-types:
          - "minor"
          - "patch"

      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.dokka*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"  # For workflow updates - no version impact

